### ISSUE TITLE
In init migration, connection is not available.

### ISSUE THREAD

**Issue by koheisg** [CakeDC/migrations#201]
this problem occur in first migration.

```
$ Console/cake Migrations.migration status -c test
Cake Migration Shell
---------------------------------------------------------------
Error: Table "schema_migrations" already exists in database.
#0 /Users/kohei-sugi/Sites/cakephp-2.6.1/Plugin/Migrations/Lib/CakeMigration.php(242): CakeMigration->_run()
#1 /Users/kohei-sugi/Sites/cakephp-2.6.1/Plugin/Migrations/Lib/MigrationVersion.php(378): CakeMigration->run('up')
#2 /Users/kohei-sugi/Sites/cakephp-2.6.1/Plugin/Migrations/Lib/MigrationVersion.php(107): MigrationVersion->_initMigrations()
#3 /Users/kohei-sugi/Sites/cakephp-2.6.1/Plugin/Migrations/Console/Command/MigrationShell.php(105): MigrationVersion->__construct(Array)
#4 /Users/kohei-sugi/Sites/cakephp-2.6.1/Vendor/cakephp/cakephp/lib/Cake/Console/Shell.php(437): MigrationShell->startup()
#5 /Users/kohei-sugi/Sites/cakephp-2.6.1/Vendor/cakephp/cakephp/lib/Cake/Console/ShellDispatcher.php(209): Shell->runCommand('status', Array)
#6 /Users/kohei-sugi/Sites/cakephp-2.6.1/Vendor/cakephp/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /Users/kohei-sugi/Sites/cakephp-2.6.1/demo/Console/cake.php(48): ShellDispatcher::run(Array)
#8 {main}
```

I resolved follow code, but this is monkey patch...
I don't know cake migrations way.

```
/**
 * Run migration
 *
 * @param string $direction Direction of migration process (up or down)
 * @return bool Status of the process
 * @throws MigrationException
 */
	public function run($direction) {
		$this->connection = 'test';
		if (!in_array($direction, array('up', 'down'))) {
			throw new MigrationException($this, sprintf(
				__d('migrations', 'Migration direction (%s) is not one of valid directions.'), $direction
			), E_USER_NOTICE);
		}

```

**Comment by koheisg** [comment]
My command is wrong.
I should use `-i` option...

thanks

**Comment by deizel** [comment]
Closing as it seems you've resolved the issue.
