### ISSUE TITLE
generateModel() creates model instances but cake loads associated models automatically

### ISSUE THREAD

**Issue by burzum** [CakeDC/migrations#304]
Cake or the Migrations plugin is using models from the app when it should not because generateModel() is used to explicitly avoid that. But for some reason the core or the plugin includes a model that is not used in the migration at all. See the stack trace provided below.

I've tried changing the AppModel to Model that is used inside generateModel() but it didn't help. I think it's the automagic of the core that tries to resolve the assocs by convention. However, this is pretty annoying because it is not the behavior I expected when using generateModel().

I've worked around that issue in this case by using query() and sending a delete query manually instead of messing any longer with this.

```php
<?php
class RemoveInactiveProjects extends CakeMigration {

/**
 * Migration description
 *
 * @var string
 */
	public $description = 'remove_inactive_projects';

/**
 * Actions to be performed
 *
 * @var array $migration
 */
	public $migration = array(
		'up' => array(
		),
		'down' => array(
		),
	);

/**
 * Before migration callback
 *
 * @param string $direction Direction of migration process (up or down)
 * @return bool Should process continue
 */
	public function before($direction) {
		if ($direction === 'before') {
			$this->removeInactiveProjects();
		}
		return true;
	}

/**
 * After migration callback
 *
 * @param string $direction Direction of migration process (up or down)
 * @return bool Should process continue
 */
	public function after($direction) {
		return true;
	}

	public function removeInactiveProjects() {
		$fileRoot = APP . 'FileStorage';
		$projects = $this->generateModel('Projects', 'projects');
		$projects->bindModel([
			'hasMany' => [
				'ProjectI18ns' => [
					'foreignKey' => 'project_id',
					'dependent' => true,
				],
				'ProjectPicture' => array(
					//'className' => 'ProjectPicture',
					'foreignKey' => 'project_id',
					'dependent' => true,
				),
				'DomainsProjects' => array(
					//'className' => 'Award',
					'foreignKey' => 'project_id',
					'dependent' => true,
				),
				'Award' => array(
					//'className' => 'Award',
					'foreignKey' => 'project_id',
					'dependent' => true,
				),
				'ProjectRightColumnBlock' => array(
					//'className' => 'ProjectRightColumnBlock',
					'foreignKey' => 'project_id',
					'dependent' => false,
				)
			]
		], false);

		$images = $this->generateModel('ImageFileStorage', 'image_file_storage');
		$images->tablePrefix = '';
		$imageI18ns = $this->generateModel('ImageFileStorageTranslations', 'image_file_storage_translations');
		$imageI18ns->tablePrefix = '';

		$recordCount = $projects->find('count', [
			'conditions' => [
				'Projects.active' => 0
			]
		]);
		$chunkSize = 100;
		$chunkCount = 0;

		while ($chunkCount < $recordCount) {
			$results = $projects->find('all', [
				'fields' => [
					'Projects.id'
				],
				'conditions' => [
					'Projects.active' => 0
				],
				'offset' => $chunkCount,
				'limit' => $chunkSize
			]);

			foreach ($results as $project) {
				$projectId = $project['Projects']['id'];

				$imageFiles = $images->find('all', [
					'conditions' => [
						'ImageFileStorage.model' => 'Projects',
						'ImageFileStorage.foreign_key' => $projectId
					]
				]);

				if (!empty($imageFiles)) {
					foreach ($imageFiles as $imageFile) {
						$path = $fileRoot . $imageFile['ImageFileStorage']['path'];
						$path = dirname($path);

						if (is_dir($path)) {
							$folder = new Folder($path);
							$folder->delete($path);
						} else {
							echo sprintf('Could not delete folder: %s', $path) . "\n";
						}

						$images->delete($imageFile['ImageFileStorage']['id']);
						$imageI18ns->deleteAll([
							'ImageFileStorageTranslations.id' => $imageFile['ImageFileStorage']['id']
						]);
					}
				}

				$projects->delete($projectId);
			}

			$chunkCount++;
			echo sprintf('Processed %d of %d', $chunkCount, $recordCount) . "\n";
		}
	}
}
```

```
C:\xampp\htdocs\wa\app>Console\cake migrations run up
 
Cake Migration Shell
---------------------------------------------------------------
Running migrations:
Error: Table wa_project_facts_figures for model ProjectFactsFigure was not found in datasource default.
#0 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(3667): Model->setSource('project_facts_f...')
#1 C:\xampp\htdocs\wa\app\Plugin\Search\Model\Behavior\SearchableBehavior.php(62): Model->getDataSource()
#2 C:\xampp\htdocs\wa\app\Plugin\Search\Model\Behavior\SearchableBehavior.php(52): SearchableBehavior->_setEscapeChars(Object(ProjectFactsFigure))
#3 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\BehaviorCollection.php(145): SearchableBehavior->setup(Object(ProjectFactsFigure), Array)
#4 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\BehaviorCollection.php(66): BehaviorCollection->load('Search.Searchab...', Array)
#5 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(781): BehaviorCollection->init('ProjectFactsFig...', Array)
#6 C:\xampp\htdocs\wa\app\Model\AppModel.php(94): Model->__construct(NULL, 'default')
#7 [internal function]: AppModel->__construct(Array)
#8 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Utility\ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#9 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(1084): ClassRegistry::init('ProjectFactsFig...')
#10 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(893): Model->_constructLinkedModel('ProjectFactsFig...', 'ProjectFactsFig...', NULL)
#11 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(926): Model->__isset('ProjectFactsFig...')
#12 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(1131): Model->__get('ProjectFactsFig...')
#13 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(1054): Model->_generateAssociation('hasAndBelongsTo...', 'ProjectFactsFig...')
#14 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(780): Model->_createLinks()
#15 C:\xampp\htdocs\wa\app\Model\AppModel.php(94): Model->__construct('building_types', 'default')
#16 [internal function]: AppModel->__construct(Array)
#17 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Utility\ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#18 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(1084): ClassRegistry::init('ProjectBuilding...')
#19 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(893): Model->_constructLinkedModel('ProjectBuilding...', 'ProjectBuilding...', NULL)
#20 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(926): Model->__isset('ProjectBuilding...')
#21 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(1131): Model->__get('ProjectBuilding...')
#22 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(1054): Model->_generateAssociation('hasAndBelongsTo...', 'ProjectBuilding...')
#23 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(780): Model->_createLinks()
#24 C:\xampp\htdocs\wa\app\Model\AppModel.php(94): Model->__construct(NULL, 'default')
#25 [internal function]: AppModel->__construct(Array)
#26 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Utility\ClassRegistry.php(169): ReflectionClass->newInstance(Array)
#27 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(1084): ClassRegistry::init('Project')
#28 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(893): Model->_constructLinkedModel('Project', 'Project', NULL)
#29 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Datasource\DboSource.php(2271): Model->__isset('Project')
#30 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Datasource\Database\Mysql.php(435): DboSource->_getJoins(Object(ProjectPicture))
#31 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(2721): Mysql->delete(Object(ProjectPicture), Array)
#32 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(2780): Model->delete('65465')
#33 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Model\Model.php(2701): Model->_deleteDependent('26563', true)
#34 C:\xampp\htdocs\wa\app\Config\Migration\1492695578_remove_inactive_projects.php(132): Model->delete('26563')
#35 C:\xampp\htdocs\wa\app\Plugin\Migrations\Lib\MigrationVersion.php(305): RemoveInactiveProjects->removeInactiveProjects(Array)
#36 C:\xampp\htdocs\wa\app\Plugin\Migrations\Lib\MigrationVersion.php(371): MigrationVersion->getMigration('1492695578_remo...', 'RemoveInactiveP...', 'app', Array)
#37 C:\xampp\htdocs\wa\app\Plugin\Migrations\Console\Command\MigrationShell.php(319): MigrationVersion->run(Array)
#38 C:\xampp\htdocs\wa\app\Plugin\Migrations\Console\Command\MigrationShell.php(295): MigrationShell->_execute(Array, true)
#39 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Console\Shell.php(458): MigrationShell->run()
#40 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Console\ShellDispatcher.php(219): Shell->runCommand('run', Array)
#41 C:\xampp\htdocs\wa\app\Vendor\cakephp\cakephp\lib\Cake\Console\ShellDispatcher.php(66): ShellDispatcher->dispatch()
#42 C:\xampp\htdocs\wa\app\Console\cake.php(34): ShellDispatcher::run(Array)
```

**Comment by pmoraes** [comment]
Hi @burzum, I'm working in this issue. But it seems to be a core issue not an issue in the plugin. I'll let you soon
